import { ReactNode } from 'react';
import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
import './globals.css';
import { css } from 'styled-system/css';
import { flex } from 'styled-system/patterns';
import Nav from './nav';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: ReactNode }) => (
  <html lang='en'>
    <head>
      <link rel='preconnect' href='https://fonts.googleapis.com' />
      <link
        rel='preconnect'
        href='https://fonts.gstatic.com'
        crossOrigin='anonymous'
      />
      <link
        href='https://fonts.googleapis.com/css2?family=Arvo&family=Heebo&display=swap'
        rel='stylesheet'
      />
    </head>
    <body className={css({ textStyle: 'body' })}>
      <div
        className={flex({
          h: '100vh',
          w: '100vw',
        })}
      >
        <div className={css({ w: '100%' })}>
          <Nav />
          {children}
        </div>
      </div>
    </body>
  </html>
);

export default RootLayout;
